### ISSUE TITLE
build folder is read only when running on mac os x - causing failure

### ISSUE THREAD

**Issue by GreatCall-EconomousT** [ionscript/grunt-closure-compiler-build#2]
When using grunt-closure-compiler-build node module on mac the build folder that is created is read only. So closure compiler download, unzipping, or anything else that happens in the build folder will fail.

The access mode 777 decimal is passed to fs.mkdirSync but is converted to 1411 octal giving folder permission 411. Which results in read only. If the 777 is omitted from mkdirSync then it will default to 0777 and fix the problem.

**Comment by GreatCall-EconomousT** [comment]
@ionscript are you still maintaining this node module?

**Comment by ionscript** [comment]
Sorry, was in holiday..
I will fix this bug.

**Comment by lisakh** [comment]
Hello,

we have a similar behaviour on linux machines, I guess it's the same problem. Is there any plan to fixed this?

Thanks

**Comment by alancnet** [comment]
I submitted a pull request to fix this bug: 
https://github.com/ionscript/grunt-closure-compiler-build/pull/3

**Comment by alancnet** [comment]
Work-around for now: use grunt-mkdir to make the directory before grunt-closure-compiler-build creates it incorrectly.

**Comment by ionscript** [comment]
Fixed in new version - 1.3.0.
Please use Version - 1.3.0.
Version 1.0.1 is deprecated.
Many Thanks!
