### ISSUE TITLE
Grunt task is stuck after unzipping the last file

### ISSUE THREAD

**Issue by vladmm** [ionscript/grunt-closure-compiler-build#4]
The closure zip is downloaded and unzipped correctly but the grunt task is stuck after unzipping is done.
Output:

```
Running "closure-compiler-build:build" (closure-compiler-build) task
Compiler downloaded: "node_modules/grunt-closure-compiler-build/build/compiler.zip" : 6038033 bytes
UNZIP ENTRY: "node_modules/grunt-closure-compiler-build/build/compiler.jar... OK
UNZIP ENTRY: "node_modules/grunt-closure-compiler-build/build/COPYING... OK
UNZIP ENTRY: "node_modules/grunt-closure-compiler-build/build/README.md... OK
```

The grunt build is stuck after this line with no error message.

The closure-compiler-build task is configured like this:

```
'closure-compiler-build': {
    build: {
        url: 'http://dl.google.com/closure-compiler/compiler-latest.zip',
        dir: 'node_modules/grunt-closure-compiler-build/build/',
        filename: 'compiler.zip'
    }
}
```

 in `grunt.initConfig` and loaded using `grunt.loadNpmTasks('grunt-closure-compiler-build');` as suggested in the `readme` file.

**Comment by ionscript** [comment]
Fixed in new version - 1.3.0.
Please use Version - 1.3.0.
Version 1.0.1 is deprecated.
Many Thanks!
